Feature/impact component
Girl-Code-It/Girl-Code-It-Website pull request #19
Opened 2020-06-27 16:17 UTC by Meghag5

2020-06-28 18:10 UTC, Meghag5 commented
changes made

2020-07-04 06:07 UTC, SinghVikram97 commented on src/Components/Impact.js
> +import styles from "./Css/Impact.module.css";
It should be **../css**

2020-07-04 06:10 UTC, SinghVikram97 requested changes
Make it responsive according to different screen sizes. Also, make impact cards a little bigger as can be seen in the design. Add <hr/> Above the component also, refer to the design file.

2020-07-05 18:34 UTC, closed without merging

2020-07-05 18:34 UTC, Meghag5 commented
new changes made