discord link added to homepage as well as in oneCodeMaps
Girl-Code-It/Girl-Code-It-Website pull request #191
Opened 2021-06-09 15:50 UTC by paarth17032000

# Description

I have added the discord link in and the discord icon on left with other icons on homepage, also I have added a **Discuss Doubts here** button in every codemap which comes from the json file and is passed as prop with other props such as submit, title etc..

Fixed #188 

## Type of change

Please check options that are relevant to your PR.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

2021-06-15 07:36 UTC, Manvityagi approved these changes

2021-06-15 07:41 UTC, Manvityagi requested changes
Hey, everything else looks good, @parth17032000, but can you commit the package-lock.json file, you have deleted it.

2021-06-19 18:02 UTC, paarth17032000 commented
@Manvityagi I have added the package-lock.json file please check and let me know if there is any issue

2021-06-20 05:20 UTC, Manvityagi approved these changes
Looks good @paarth17032000.

2021-06-20 05:20 UTC, merged