Feature/banner component
Girl-Code-It/Girl-Code-It-Website pull request #20
Opened 2020-06-27 16:43 UTC by prachibansal2000

2020-06-28 16:42 UTC, prachibansal2000 commented
added styles in banner

2020-06-28 16:47 UTC, SinghVikram97 commented
Is it done fully, should I check?

2020-07-04 04:31 UTC, SinghVikram97 commented on src/Components/Banner.js
> +          your <span className={`${styles.dreams}`}>dreams</span>
Use className={style.dreams} instead of {`${styles.dreams}}.
Change it for remaining classNames also which have only custom CSS.

2020-07-04 04:32 UTC, SinghVikram97 commented on src/Components/Banner.js
> +          <button className={`border-0 ${styles.btn1}`}>About Us</button>
This is fine `className={`border-0 ${styles.btn1}`}` when using bootstrap+custom css use this syntax

2020-07-04 04:34 UTC, SinghVikram97 requested changes
Please see the code review

2020-07-04 04:35 UTC, SinghVikram97 commented
Make it responsive. It doesn't match with design on my screen size. Also, make it responsive for mobile devices.

2020-07-04 10:05 UTC, prachibansal2000 commented
okay i will make all the changes

2020-07-05 11:14 UTC, closed without merging