Added 4 more Impact-Component cards
Girl-Code-It/Girl-Code-It-Website pull request #49
Opened 2020-08-09 17:13 UTC by Meghag5

(feature/Impact-Component)-Added Impact component

# Description

Added 4 more cards Impact Component 

Fixed #47 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-08-09 19:33 UTC, vinitshahdeo requested changes
@Meghag5 Hey, I've added a few comments, please do have a look!

2020-08-09 19:33 UTC, vinitshahdeo commented on src/Components/Impact.js
> +          >
@Meghag5 The below component is repeated multiple times, can't we have a map over a JSON?
```js
<ImpactCard
   impact={{
       name: "Open-Source Journey",
       imgUrl: "image3.svg",
       para1:
          "Get your journey in open-source started with our open-source projects!",
                para2: "",
    }}
 />
```

2020-08-09 19:33 UTC, vinitshahdeo commented on src/Components/Impact.js
> +            style={{ marginTop: "5px" }}
@Meghag5 Please try to avoid inline styling. It's not a good practice as it will be a problem when we scale our system.

2020-08-10 15:05 UTC, Manvityagi requested changes

2020-08-10 15:05 UTC, Manvityagi commented on src/Components/Impact.js
> +      people: [
@Meghag5 Give meaningful names to vars always, change people to impactCards

2020-08-10 16:01 UTC, Manvityagi requested changes

2020-08-10 16:01 UTC, Manvityagi commented on src/Components/Impact.js
> +      impactcards: [
impactCards not impactcards 
That's the camelCase convention 

@Meghag5

2020-08-10 16:06 UTC, merged