(fix/RestructuredComponents)-Restructured and Routed Components
Girl-Code-It/Girl-Code-It-Website pull request #51
Opened 2020-08-10 17:31 UTC by harsha14gupta

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #46 
Added dependencies:
react-router-dom": "5.2.0"
"react-scroll": "1.8.0"

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-08-10 19:04 UTC, Manvityagi approved these changes

2020-08-10 20:29 UTC, vinitshahdeo requested changes
@harsha14gupta Added a few more comments.

2020-08-10 20:29 UTC, vinitshahdeo commented on src/homepage/Components/Impact.js
> +          para2: ""
@harsha14gupta Though it's an optional change but ideally we should keep such hardcoded JSON out of the component. Can we have `ImpactData.js` file outside and import it here?

2020-08-10 20:29 UTC, vinitshahdeo commented on src/homepage/Components/Banner.js
>        <br />
@harsha14gupta Why these many `<br />` statements? Can't have CSS for `padding-bottom` / `margin-bottom`?

2020-08-11 06:10 UTC, vinitshahdeo approved these changes
Good job @harsha14gupta 👏

2020-08-11 07:15 UTC, merged